import Cards from "../Components/Cards/Cards";

const restaurantsCards = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "332231",
      name: "Tossin Pizza",
      uuid: "c332e826-4fbb-4c6a-9de6-c51d70154bcc",
      city: "2",
      area: "Sector 56",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "313485a665bd0f4958fdc14ead8afade",
      cuisines: ["Pizzas", "Italian", "Beverages", "Desserts"],
      tags: [],
      costForTwo: 60000,
      costForTwoString: "₹600 FOR TWO",
      deliveryTime: 45,
      minDeliveryTime: 25,
      maxDeliveryTime: 35,
      slaString: "25-35 MINS",
      lastMileTravel: 5,
      slugs: {
        restaurant: "tossin-pizza-tossin_jalvayu-towers-tossin_jalvayu-towers",
        city: "gurgaon",
      },
      cityState: "2",
      address: "SCO 32, 1st Floor, Sector 56, Gurgaon",
      locality: "Sector 56",
      parentId: 1778,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "10% off",
        shortDescriptionList: [
          {
            meta: "10% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "10% off up to ₹40 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "10% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "10% off up to ₹40 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [
        {
          tradeCampaignHeaders: [],
          avgRating: "4.2",
          totalRatings: 1000,
          area: "Sector 50",
          city: "2",
          locality: "Sector 50",
          deliveryTime: 30,
          minDeliveryTime: 25,
          maxDeliveryTime: 35,
          slaString: "25-35 MINS",
          select: false,
          id: "332226",
          slugs: {
            restaurant: "tossin-pizza-tossin_sohna-road-tossin_sohna-road",
            city: "gurgaon",
          },
          feeDetails: {
            restaurant_id: 332226,
            fees: [
              {
                name: "distance",
                fee: 0,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            total_fee: 0,
            message: "",
            title: "Delivery Charge",
            amount: "0",
            icon: "",
          },
          promoted: false,
          adTrackingID: "",
          aggregatedDiscountInfo: {
            header: "10% off",
            shortDescriptionList: [
              {
                meta: "10% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off up to ₹40 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
        },
        {
          tradeCampaignHeaders: [],
          avgRating: "4.3",
          totalRatings: 1000,
          area: "DLF Phase 4",
          city: "2",
          locality: "DLF Galleria",
          deliveryTime: 45,
          minDeliveryTime: 25,
          maxDeliveryTime: 35,
          slaString: "25-35 MINS",
          select: false,
          id: "332229",
          slugs: {
            restaurant: "tossin-pizza-tossin_dlf-phase-4-tossin_dlf-phase-4",
            city: "gurgaon",
          },
          feeDetails: {
            restaurant_id: 332229,
            fees: [
              {
                name: "distance",
                fee: 0,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            total_fee: 0,
            message: "",
            title: "Delivery Charge",
            amount: "0",
            icon: "",
          },
          promoted: false,
          adTrackingID: "",
          aggregatedDiscountInfo: {
            header: "30% off",
            shortDescriptionList: [
              {
                meta: "30% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
        },
      ],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 0,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 0,
        message: "",
        title: "Delivery Charge",
        amount: "0",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7356959~p=1~eid=00000189-2044-02a3-2e9b-b6860021010d~srvts=1688463475363",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "332231",
        deliveryTime: 45,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "557228",
      name: "Chef Mantra",
      uuid: "849fab30-f32e-492e-a7ef-80daba41b82a",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "h7wbfbhtwsagfa4ecklk",
      cuisines: ["North Indian", "Chinese", "Snacks"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 61,
      minDeliveryTime: 61,
      maxDeliveryTime: 61,
      slaString: "61 MINS",
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: "chef-mantra-old-gurgaon-(zone-6)-old-gurgaon-(zone-6)",
        city: "gurgaon",
      },
      cityState: "2",
      address:
        "Jal Vihar, Jal Vihar Colony, Sector 46, Gurugram, Haryana 122003",
      locality: "Jal Vihar Colony",
      parentId: 334962,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "FLAT125 off",
        shortDescriptionList: [
          {
            meta: "FLAT125 off | Use FLATDEAL",
            discountType: "Flat",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "FLAT125 off | Use FLATDEAL",
            discountType: "Flat",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "₹125 OFF",
        shortDescriptionList: [
          {
            meta: "Use FLATDEAL",
            discountType: "Flat",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "FLAT125 off | Use FLATDEAL",
            discountType: "Flat",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "557228",
        deliveryTime: 61,
        minDeliveryTime: 61,
        maxDeliveryTime: 61,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "639000",
      name: "Chaayos Chai+Snacks=Relax",
      uuid: "22e4f50e-29d4-4409-af99-e4161d863c91",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "2beebd3688e63e027ee8a11c1c8a72c8",
      cuisines: [
        "Bakery",
        "Beverages",
        "Chaat",
        "Desserts",
        "Home Food",
        "Italian",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "Sweets",
      ],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 59,
      minDeliveryTime: 59,
      maxDeliveryTime: 59,
      slaString: "59 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "chaayos-chaisnacksrelax-sector-46-sohna-road",
        city: "gurgaon",
      },
      cityState: "2",
      address:
        "Unit No. DSS No.23, Sector- 46, Gurgaon, Gurugram, Haryana-122003",
      locality: "Huda Colony",
      parentId: 281782,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "60% off",
        shortDescriptionList: [
          {
            meta: "60% off | Use STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "60% off up to ₹120 | Use code STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "60% OFF",
        shortDescriptionList: [
          {
            meta: "Use STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "60% off up to ₹120 | Use code STEALDEAL",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      sla: {
        restaurantId: "639000",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "274841",
      name: "Mealful Rolls - India's Biggest Rolls",
      uuid: "52ef6f23-bf0b-4256-aee6-5f6fd36759c3",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "mbkxpg6xxyfzrawmb0hj",
      cuisines: ["Fast Food", "Snacks", "North Indian", "Desserts"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 26,
      minDeliveryTime: 21,
      maxDeliveryTime: 31,
      slaString: "21-31 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant:
          "mealful-wraps-meals-in-a-wrap-sector-46-gurgaon-jalvayu-towers",
        city: "gurgaon",
      },
      cityState: "2",
      address: "PLOT No. 3152-P, SECTOR 46, Gurgaon(Haryana) -122003",
      locality: "Sohna Road",
      parentId: 10390,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "20% off",
        shortDescriptionList: [
          {
            meta: "20% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "20% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7353403~p=4~eid=00000189-2044-02a3-2e9b-b6870021043a~srvts=1688463475363",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "274841",
        deliveryTime: 26,
        minDeliveryTime: 21,
        maxDeliveryTime: 31,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "608566",
      name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
      uuid: "1c9cedaf-433f-4d74-a2b5-7b1c3e81b212",
      city: "2",
      area: "Sector 39",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "o5foezbu02vciargr1ve",
      cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 59,
      minDeliveryTime: 59,
      maxDeliveryTime: 59,
      slaString: "59 MINS",
      lastMileTravel: 1.5,
      slugs: {
        restaurant:
          "kwality-walls-frozen-dessert-and-ice-cream-shop-sohna-road-sohna-road-9",
        city: "gurgaon",
      },
      cityState: "2",
      address:
        "K.S. ENTERPRISES: H.NO:553, V.P.O JHARSA PATTI CHOPRA, ISLAMPUR(97), GURGAON, HARYANA- 122001 (HUL- I34A386P1732)",
      locality: "ISLAMPUR(97)",
      parentId: 582,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [
        {
          tradeCampaignHeaders: [],
          avgRating: "4.5",
          totalRatings: 100,
          area: "Adampur",
          city: "2",
          locality: "Durga Colony",
          deliveryTime: 57,
          minDeliveryTime: 57,
          maxDeliveryTime: 57,
          slaString: "57 MINS",
          select: false,
          id: "564007",
          slugs: {
            restaurant:
              "kwality-walls-frozen-dessert-and-ice-cream-shop-huda-city-huda-city-7",
            city: "gurgaon",
          },
          feeDetails: {
            restaurant_id: 564007,
            fees: [
              {
                name: "distance",
                fee: 3500,
                message: "",
              },
              {
                name: "rain",
                fee: 2000,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
            ],
            total_fee: 5500,
            message: "",
            title: "Delivery Charge",
            amount: "5500",
            icon: "",
          },
          promoted: false,
          adTrackingID: "",
        },
      ],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "608566",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        lastMileTravel: 1.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.8",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "443521",
      name: "NH1 Bowls - Highway To North",
      uuid: "3b7e5ad3-1052-4347-ae0c-6a0834728076",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "dtpe6uhzmprvmocsmjlj",
      cuisines: ["North Indian", "Punjabi", "Home Food"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 13,
      maxDeliveryTime: 23,
      slaString: "13-23 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant:
          "nh1-bowls-highway-to-north-sector-46-gurgaon-jalvayu-towers",
        city: "gurgaon",
      },
      cityState: "2",
      address: "PLOT No. 3152-P, SECTOR 46, Gurgaon(Haryana) -122003",
      locality: "Sohna Road",
      parentId: 22452,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "20% off",
        shortDescriptionList: [
          {
            meta: "20% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "20% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7353407~p=7~eid=00000189-2044-02a3-2e9b-b6880021072f~srvts=1688463475363",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "443521",
        deliveryTime: 18,
        minDeliveryTime: 13,
        maxDeliveryTime: 23,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.2",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "712793",
      name: "Khana khazana",
      uuid: "e43f7961-4724-4a60-bd10-1367be7b8545",
      city: "2",
      area: "Rodeo Drive Shopping Complex",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "51e4bee5548319fa7abe7582158fd164",
      cuisines: [
        "North Indian",
        "Chinese",
        "Tandoor",
        "Biryani",
        "Thalis",
        "Fast Food",
      ],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 59,
      minDeliveryTime: 59,
      maxDeliveryTime: 59,
      slaString: "59 MINS",
      lastMileTravel: 2.5,
      slugs: {
        restaurant: "khana-khazana-cyber-city-cyber-city-2",
        city: "gurgaon",
      },
      cityState: "2",
      address:
        "Shop No DG-24, Ground Floor, Rodeo Drive Shopping Complex, South City-2,, Shamshpur(92), Gurgaon, Gurugram, Haryana - 122018",
      locality: "Dlf City Court",
      parentId: 2928,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "65% off",
        shortDescriptionList: [
          {
            meta: "65% off on all orders",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "65% off on all orders",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "65% OFF",
        shortDescriptionList: [
          {
            meta: "",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "65% off on all orders",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "712793",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        lastMileTravel: 2.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 50,
      new: true,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "289291",
      name: "BOX8 - Desi Meals",
      uuid: "353b2e89-0cac-4fbb-ad8d-f31640870488",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "2c36db5027b5abe00ccc15bf455ea70b",
      cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 13,
      maxDeliveryTime: 23,
      slaString: "13-23 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: "box8-desi-meals-sector-46-gurgaon-jalvayu-towers",
        city: "gurgaon",
      },
      cityState: "2",
      address: "PLOT No. 3152-P, SECTOR 46, Gurgaon(Haryana) -122003",
      locality: "Sohna Road",
      parentId: 10655,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "20% off",
        shortDescriptionList: [
          {
            meta: "20% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "20% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "289291",
        deliveryTime: 18,
        minDeliveryTime: 13,
        maxDeliveryTime: 23,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "392509",
      name: "Gianis - Ice Cream, Shakes & Sundaes",
      uuid: "2f3bde74-5eac-429f-a9f6-5c6c0906bf46",
      city: "2",
      area: "sohna road",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "fswsfypczxffoukivgmq",
      cuisines: ["Ice Cream", "Beverages"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 56,
      minDeliveryTime: 56,
      maxDeliveryTime: 56,
      slaString: "56 MINS",
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: "giani's-sohna-road-sohna-road-3",
        city: "gurgaon",
      },
      cityState: "2",
      address: "Shop No 49, Huda Market, sector 46, gurgaon, haryana",
      locality: "Huda Colony",
      parentId: 380244,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "392509",
        deliveryTime: 56,
        minDeliveryTime: 56,
        maxDeliveryTime: 56,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "53056",
      name: "Giani Ice Cream",
      uuid: "3a45e570-e4ff-4e67-be9d-90384b04acf5",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "bvfwukcctyecaojod4q7",
      cuisines: ["Ice Cream", "Desserts"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 59,
      minDeliveryTime: 59,
      maxDeliveryTime: 59,
      slaString: "59 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "giani-sector-45-huda-city",
        city: "gurgaon",
      },
      cityState: "2",
      address:
        "Shop 88, Ground Floor, HUDA Market, Sector 46, Near Sector 45, Gurgaon",
      locality: "Huda Market",
      parentId: 6577,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "40% off",
        shortDescriptionList: [
          {
            meta: "40% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "40% off up to ₹80 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "40% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "40% off up to ₹80 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      sla: {
        restaurantId: "53056",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "313629",
      name: "Itminaan Matka Biryani - Slow Cooked",
      uuid: "e61290ac-ee7f-4eca-80a8-6522f3b3b48d",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "htbljboz0ylfyzdlg2ql",
      cuisines: ["Biryani", "North Indian", "Mughlai"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 26,
      maxDeliveryTime: 36,
      slaString: "26-36 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant:
          "itminaan-dum-pukht-biryani-sector-46-gurgaon-jalvayu-towers",
        city: "gurgaon",
      },
      cityState: "2",
      address: "PLOT No. 3152-P, SECTOR 46, Gurgaon(Haryana) -122003",
      locality: "Sohna Road",
      parentId: 107673,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "20% off",
        shortDescriptionList: [
          {
            meta: "20% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "20% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "313629",
        deliveryTime: 31,
        minDeliveryTime: 26,
        maxDeliveryTime: 36,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "287696",
      name: "Nirula's",
      uuid: "ed142875-1541-4e4e-a84c-9f636976b807",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "2320ea078c38eabec536608f49454051",
      cuisines: ["Ice Cream", "Desserts", "Beverages"],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 54,
      minDeliveryTime: 54,
      maxDeliveryTime: 54,
      slaString: "54 MINS",
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: "nirula's-sohna-road-sohna-road",
        city: "gurgaon",
      },
      cityState: "2",
      address: "Shop No - 39, Huda market, Sector 46, Gurugram",
      locality: "Huda Colony",
      parentId: 1738,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "287696",
        deliveryTime: 54,
        minDeliveryTime: 54,
        maxDeliveryTime: 54,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.5",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "14717",
      name: "Delish Bake N Choc",
      uuid: "da6704ad-e265-4145-bcb0-e37a9cc839aa",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "isd4phalpmg593qvvhmc",
      cuisines: ["Desserts", "Continental"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 59,
      minDeliveryTime: 59,
      maxDeliveryTime: 59,
      slaString: "59 MINS",
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: "delish-bake-n-choc-sector-45-huda-city",
        city: "gurgaon",
      },
      cityState: "2",
      address: "SCO 108-109, Huda Market, Sector 46, Gurgaon",
      locality: "Huda Market",
      parentId: 70597,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5500,
        message: "",
        title: "Delivery Charge",
        amount: "5500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "14717",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "443520",
      name: "ZAZA Mughal Biryani",
      uuid: "2f2e3c32-b5a5-40cd-b623-e750f109ebfb",
      city: "2",
      area: "Sector 45",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "990cd5861ab70e380542b4da9d35d97b",
      cuisines: ["Biryani", "North Indian", "Awadhi"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 20,
      minDeliveryTime: 15,
      maxDeliveryTime: 25,
      slaString: "15-25 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: "zaza-21-spice-biryani-sector-46-gurgaon-jalvayu-towers",
        city: "gurgaon",
      },
      cityState: "2",
      address: "PLOT No. 3152-P, SECTOR 46, Gurgaon(Haryana) -122003",
      locality: "Sohna Road",
      parentId: 22473,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "20% off",
        shortDescriptionList: [
          {
            meta: "20% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "20% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "443520",
        deliveryTime: 20,
        minDeliveryTime: 15,
        maxDeliveryTime: 25,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "622053",
      name: "MOJO Pizza - 2X Toppings",
      uuid: "03eefe8f-a39e-4029-a919-93478d336890",
      city: "2",
      area: "GUR_Sohna Road",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "50605611aea3b0df713c9692403e5134",
      cuisines: ["Pizzas", "Italian", "Fast Food", "Desserts"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 20,
      maxDeliveryTime: 30,
      slaString: "20-30 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: "mojo-pizza-2x-topping-sector-46-sohna-road",
        city: "gurgaon",
      },
      cityState: "2",
      address: "PLOT No. 3152-P, SECTOR 46, Gurgaon(Haryana) -122003",
      locality: "Sector 46",
      parentId: 11329,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "20% off",
        shortDescriptionList: [
          {
            meta: "20% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "20% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "20% off up to ₹50 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "622053",
        deliveryTime: 25,
        minDeliveryTime: 20,
        maxDeliveryTime: 30,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.5",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
];

const cardStyle = {
  display: "flex",
  flexWrap: "wrap",
  margin: "4%",
  paddingTop: "150px",
  justifyContent: "center",
};

const Home = () => {
  return (
    <>
      <div className="card-container" style={cardStyle}>
        {restaurantsCards.map((restaurants) => {
          return <Cards key={restaurants.data.id} data={restaurants} />;
        })}
      </div>
    </>
  );
};

export default Home;
